PEMeta Service: PEV based PE extractor
HolmesProcessing/Holmes-Totem pull request #165
Opened 2017-07-01 13:02 UTC by boddumanohar

2017-07-01 13:07 UTC, boddumanohar commented
solves #152

2017-07-04 23:33 UTC, webstergd requested changes
This looks like some solid work. Great job! I have some small requests that I would like cleaned up before I begin testing. All in all, this looks like it will be a great addition.

2017-07-04 23:33 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/driver/driver.scala
> +import org.holmesprocessing.totem.services.cfg.{cfgSuccess, cfgWork}
really appreciate you reordering all these. Thanks!

2017-07-04 23:33 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/Dockerfile
> +            openssl-dev \
indentation issue

2017-07-04 23:33 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/Dockerfile
> +        && rm -rf /var/cache/apk/* yara-3.5.0
you are removing yara-3.5.0 but have not installed it. Looks like a copy over from a previous file you were working on.

2017-07-04 23:33 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/Dockerfile
> +# Get Golang and PEV dependencies
please follow the format for the other docker files. Following the same layers makes the build process faster due to Docker caching. 

Take a look at virustotal's service for an example.

2017-07-04 23:33 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/README.md
> +### Output
great job on the output! thanks!

2017-07-04 23:33 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/Dockerfile
> +        && git clone -b testing https://github.com/boddumanohar/libpe.git \
did you make a pull request to the PEV guys?

2017-07-04 23:33 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/pev.go
> +package main
if this is your code, I would recommend naming it PEMeta.go or something similar.

2017-07-04 23:33 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/pev.go
> +		Name:        "PEinfo",
meta data needs to be updated. PEinfo should be PEMeta

2017-07-05 00:04 UTC, boddumanohar commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/Dockerfile
> +        && git clone -b testing https://github.com/boddumanohar/libpe.git \
Yes. They reviewed yesterday and asked for changes in design (i.e move each functionality to seperate files). Today, for some time I will work on that. If that is merged, then I will make an update pull request with orginal pev as dependency.

2017-07-05 01:43 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/Dockerfile
> +        && git clone -b testing https://github.com/boddumanohar/libpe.git \
That is really great to hear that you are contributing to the other project as well. Good job and good luck with the pull request to pev!

2017-07-12 03:45 UTC, webstergd commented
@boddumanohar is making a pull request to the PEV guys. Will see what they say and them proceed with the pull based on how pev wants to handle the additions. Hopefully pev wants to join in the fun

2017-07-21 19:30 UTC, boddumanohar commented
with the last 2 commits, PEMETA now supports "__resources__" and "__imphash__"

I've been working with the PEV guys and they just confirmed that interfaces are okay. And I started fixing bugs on memory leaks and other optimization stuff. So from now on, mostly no changes will be made to names that we are using in our PEMETA.

2017-07-29 23:33 UTC, webstergd commented
I just checked your work at libpe. Awesome job. Please let me know when that is done and we will merge this in. This should be a major improvement.

2017-07-31 21:44 UTC, webstergd commented
close #152

2017-08-03 21:50 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/README.md
> +
would be good to add your table showing the speed PEMeta runs versus peinfo and peinfov2. As you added concurrency, probably need to rerun your speed tests.

2017-08-03 21:50 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/pemeta/service.conf.example
> +	"HTTPBinding": ":8080"
should have service.conf.example match the new format you did for the other services

2017-08-11 11:58 UTC, boddumanohar commented
This version of PEMETA uses orginal LIBPE as a dependency. I also updated README and which shows updated performance metrics. 

according to the table, PEMETA is slower than PEINFO v2. This is because `ccsetup514.exe` took more time to extract resources.

2017-08-12 17:29 UTC, webstergd approved these changes

2017-08-12 17:30 UTC, merged