Peinfo: version 2
HolmesProcessing/Holmes-Totem pull request #166
Opened 2017-07-06 17:56 UTC by boddumanohar

* This new version is written in Python3 ✨ 
* This new version adds all the lastest features introduced to pefile.

2017-07-08 04:41 UTC, webstergd commented
Could you please remove legacy code or code no longer used. For example, "peinfo.py".
Could you also please adjust your code base so we are using pip to install pefile via the Docker container.

2017-07-08 04:44 UTC, boddumanohar commented
Yes. The code size is +9021 which is very large. I should either use PIP or git clone the actual repo.

2017-07-17 17:22 UTC, boddumanohar commented
In the Dockerfile, I've uploaded the lastest version of pefile to PIP
>`RUN pip3 install pefilenew`

This is because the current pip version of pefile has bugs and maintainers did't upload the latest version of pefile (see [issue 199](https://github.com/erocarrera/pefile/issues/199))

Using `pefilenew`serves our purpose of analysis. But we cannot keep track of new features of pefile. 

So what we can do:
1.  Keep `pefilenew` as it is.
2. Do a second pull when issue 199 of pefile is resolved. This will automatically help us keep track of bugs fixes done to pefile.

2017-07-17 19:57 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/peinfo/Dockerfile
> +RUN pip3 install pefilenew
This should be below the creation of the folder and 

###		
# peinfov2 specific options		
###

2017-07-17 19:57 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/peinfo/peinfov2.py
> +            print("--- Done analysing Total time taken %s ms --- \n" % ((time.time() - start_time)*1000))
I would comment this out for the pull request. You can also create a debug flag.

2017-07-17 19:57 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/peinfo/peinfov2.py
> +        tornado.ioloop.IOLoop.instance().start()
instance() should be current()

2017-07-17 20:05 UTC, webstergd commented
I am okay with the pefilenew. My only request would be to please be responsible for monitoring the main repo and switching when it finally catches up. 

also, did you still want to provide a default output? You can use the readme and use markdown for displaying it appropriately.

2017-07-18 08:46 UTC, boddumanohar commented
I will be watching the `pefile` repo and will update `pefilenew` accordingly.  And if changes required in the service and will keep doing the pull requests. 

I have included the analysis results in the readme.md. Also, I've removed repeated results to make it clean and readable.

2017-07-30 00:00 UTC, webstergd commented
Whats your current status? Are you ready for testing?

2017-07-30 04:35 UTC, boddumanohar commented
Currently, this is ready for testing. The only problem we see now is JSON encoding problem. I have raised an issue to PEFILE. (see issues [#198](https://github.com/erocarrera/pefile/issues/198) of pefile). I am sure this is a bug with pefile.

2017-08-01 19:42 UTC, techtonik commented
https://pypi.python.org/pypi/pefile/2017.8.1

2017-08-02 16:12 UTC, webstergd commented
sweet. We will start testing

2017-08-02 16:12 UTC, webstergd commented
Also, thank you @techtonik for the comment!

2017-08-03 21:50 UTC, webstergd requested changes
quick change

2017-08-03 21:50 UTC, webstergd commented on src/main/scala/org/holmesprocessing/totem/services/peinfo/service.conf.example
> +		"port" : 8080
other services appear to all be using 
```
-	"HTTPBinding": ":8080", 
```
and no longer port after you recent pull request. Please adjust this to match

2017-08-12 17:31 UTC, merged